### ISSUE TITLE
The preview doesn't use the entire input if I type too fast

### ISSUE THREAD

**Issue by anonimitoraf** [armindarvish/consult-omni#15]
**Describe the bug**
When I type too fast, the search preview doesn't use the entire input. My config's pretty much the same as the basic example in the README

```elisp
(use-package consult-omni
  :after consult
  :config
  (require 'consult-omni-sources)
  (require 'consult-omni-embark)
  (consult-omni-sources-load-modules)
  (setq consult-omni-show-preview t
        consult-omni-default-autosuggest-command #'consult-omni-dynamic-brave-autosuggest
        consult-omni-default-interactive-command #'consult-omni-multi
        consult-omni-multi-sources '("calc"
                                     ;; "File"
                                     ;; "Buffer"
                                     ;; "Bookmark"
                                     "Apps"
                                     ;; "gptel"
                                     "Brave"
                                     "Dictionary"
                                     ;; "Google"
                                     "Wikipedia"
                                     "elfeed"
                                     ;; "mu4e"
                                     ;; "buffers text search"
                                     "Notes Search"
                                     "Org Agenda"
                                     "GitHub"
                                     ;; "YouTube"
                                     "Invidious")
        consult-omni-brave-api-key (getenv "BRAVE_API_KEY")))
```

**To Reproduce**
1. Search "something"
2. Notice that the search preview doesn't use "something". Instead it gets cutoff (see recording below)
3. Try typing a bit slower
4. Notice that it's fine this time

**Expected behavior**
I expect my input to be debounced a bit and for the search preview to use my entire input.

**Screenshots**

[Peek 2024-07-20 19-10.webm](https://github.com/user-attachments/assets/7a0ad67a-f117-40d5-a24d-2ddc2d1be243)

**Important Information:**
 - OS: Manjaro Linux
 - Version of Emacs: 29
 - Version of `consult`: 1.4
 - The installation method and the configuration you are using with your consult-omni: straight

**Comment by armindarvish** [comment]
@anonimitoraf That is weird and I cannot reproduce this. The only thing I can think of is that you are typing slow (and not fast) and you hit some API rate limits (query/seconds). What is the value of `consult-omni-dynamic-input-debounce` and `consult-async-input-debounce`?
You can try to increase the former and see if that helps. If that does not solve the issue, then you need to help me understand the issue

- What exactly do you mean by preview? I don't see any previews in that video. Do you mean results/candidates?
- Are you sure it is a matter of speed of typing? What happens if you copy and paste the phrase into the prompt (i.e. the ultimate fast input)?
- If you set `consult-omni-log-level` to `'debug`, do you see any errors either in `*Messages*`  or in `*consult-omni-log*` buffer? What do you see in hidden http buffers (that is the buffer name starts with a 'space' followed by '*http-*') for example it may look like: ` *http api.search.brave.com:443*`?
