### ISSUE TITLE
Browser History errors when part of a `consult-omni-multi`, but `consult-omni-browser-history` works fine independently

### ISSUE THREAD

**Issue by jackmac92** [armindarvish/consult-omni#29]
**Describe the bug**
When I include "Browser History" in a consult-omni-multi, I get `error in calling :items of Browser History source [N times]`

But I can't seem to make it trip the debugger with `toggle-debug-on-error`

Not a major issue, really appreciate your work on this project I'm finding it very useful

**Comment by armindarvish** [comment]
@jackmac92 That is likely a [browser-hist](https://github.com/agzam/browser-hist.el) issue. Run `browser-hist-search` and see if that works correctly. If that runs without an issue, then the `consult-omni-browser-history` should work as well. If it does not, check your browser-hist settings and try restarting your browser (that has worked for me in the past. I think it is because sometimes the files are locked and browser-hist cannot access them and restarting the browser resolves that).  

Regarding debugging, you should set `consult-omni-log-level` to `debug:

```emacs-lisp
(setq consult-omni-log-level 'debug)
```

Then you will see some error messages in the `*Messages*` buffer and depending on the error, you likely will see it when you do `toggle-debug-on-error`.

Let me know what happens when you try all that and if there is something we can do on the consult-omni side, I'll take a look at it.

**Comment by jackmac92** [comment]
Was going to investigate your suggestions but it is working now, not sure how I broke/fixed it.

But appreciate the advice on setting log-level, that will help me a lot for debugging my own issues. 

Thanks again for working on this
